### ISSUE TITLE
Highlight focused element

### ISSUE THREAD

**Issue by nipafx** [nipafx/nipafx.dev#43]
This makes keyboard navigation easier. Proposed CSS:

```css
input:focus + label {
	color: var(--alt-color) !important; /* highlight focussed menu entry */
}

input:not(:checked) + label + div {
	display: none; /* remove closed menus from the tab order */
}
```
